github.com:
    users:
        allyelvis:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: allyelvis
